github.com:
    users:
        allyelvis:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: allyelvis
